github.com:
    users:
        allyelvis:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: allyelvis
